Repository civictechindex/CTI-website-frontend, pull requests merged in 2020-09, with the labels that each got.

#64 Updating README.md to match hackforla
  README.md
Labels: documentation, front end

#78 Update README.md
  README.md
Labels: Product/Project Management, documentation, front end

#81 Adds the CTI favicon
  public/favicon.ico
Labels: enhancement, front end
