Repository civictechindex/CTI-website-frontend, pull requests merged in 2021-01, with the labels that each got.

#192 Update README.md
  README.md
Labels: bug

#154 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#235 Improve Cypress settings
  .github/workflows/ci.yml
  .nycrc.json
  cypress/.eslintrc.json
  cypress/integration/api/api.spec.js
  cypress/integration/examples/home_spec.js
  cypress/integration/pages/about.spec.js
  cypress/integration/pages/contributors.spec.js
  cypress/integration/pages/home.spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  cypress/tsconfig.json
  package-lock.json
  package.json
Labels: bug, role: front end
